Avoid tar directory traversal on sdist extract to fix CVE-2007-4559
regebro/pyroma pull request #90
Opened 2022-11-22 05:58 UTC by CAM-Gerlach

This fixes the tar directory traversal issue with Python's stdlib `tarfile` module's `extractall` function, replacing #89 and adapted from what we did in spyder-ide/spyder-kernels#428 , but greatly simplifying the implementation using `pathlib` (and making a few other tweaks to confirm with `pyroma`'s style and practices).

Closes #89

2022-11-22 10:27 UTC, regebro requested changes
In general it looks good.

2022-11-22 10:27 UTC, regebro commented on pyroma/distributiondata.py
> +        root = pathlib.Path(path).resolve()
This line could be outside, the loop, I think?
Not a big deal, I know, but still.

2022-11-23 02:30 UTC, CAM-Gerlach commented on pyroma/distributiondata.py
> +        root = pathlib.Path(path).resolve()
Yup, great point—missed that when I was refactoring this to use `pathlib`. I've pushed an update with this fixed, thanks.

2022-11-24 08:30 UTC, regebro approved these changes

2022-11-24 08:30 UTC, regebro commented
Great!

2022-11-24 08:31 UTC, merged